# Generated by Django 3.2.5 on 2021-07-22 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEVICE',
            fields=[
                ('devicecode', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ENERGYCONSUPTION',
            fields=[
                ('eneconcode', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Date Field', models.DateField()),
                ('energytoday', models.IntegerField(max_length=10)),
                ('energyyesterday', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GROUP',
            fields=[
                ('groupcode', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ROL',
            fields=[
                ('rolcode', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ROLDEVICE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('devicecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.group')),
                ('rolcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.rol')),
            ],
        ),
        migrations.CreateModel(
            name='ROLUSER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('rolcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.rol')),
            ],
        ),
        migrations.CreateModel(
            name='TYPE',
            fields=[
                ('typecode', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('usercode', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='salas',
            name='persona',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Salas',
        ),
        migrations.AddField(
            model_name='roluser',
            name='usercode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.user'),
        ),
        migrations.AddField(
            model_name='energyconsuption',
            name='groupcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.group'),
        ),
        migrations.AddField(
            model_name='device',
            name='groupcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.group'),
        ),
        migrations.AddField(
            model_name='device',
            name='typecode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.type'),
        ),
    ]
