# Generated by Django 3.0.1 on 2021-07-25 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupcode', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('typecode', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('devicecode', models.IntegerField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('groupcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Group')),
                ('typecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Type')),
            ],
        ),
    ]
