# Generated by Django 3.0.1 on 2021-07-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rolcode', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
