# Generated by Django 3.0.1 on 2021-07-25 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyConsuption',
            fields=[
                ('eneconcode', models.IntegerField(primary_key=True, serialize=False)),
                ('Date Field', models.DateField()),
                ('energytoday', models.IntegerField()),
                ('energyyesterday', models.IntegerField()),
                ('groupcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Group')),
            ],
        ),
    ]
