# Generated by Django 3.0.1 on 2021-07-25 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_energyconsuption'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('usercode', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RolUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('rolcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Rol')),
                ('usercode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.User')),
            ],
        ),
        migrations.CreateModel(
            name='RolDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('devicecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Group')),
                ('rolcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Rol')),
            ],
        ),
    ]
