# Generated by Django 3.0.1 on 2021-09-12 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_roldevice_roluser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='fathercode',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iot.Group'),
        ),
    ]
