# Generated by Django 3.0.1 on 2021-09-14 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_group_fathercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='fathercode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iot.Group'),
        ),
    ]
