# Generated by Django 3.0.1 on 2021-09-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_auto_20210914_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='topic',
            new_name='name',
        ),
    ]
