# Generated by Django 3.0.1 on 2021-10-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_auto_20210918_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
