# Generated by Django 3.0.1 on 2021-10-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0009_auto_20211003_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='rol',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
