# Generated by Django 3.0.1 on 2021-10-09 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0010_auto_20211003_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roldevice',
            name='devicecode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Device'),
        ),
        migrations.AlterUniqueTogether(
            name='roldevice',
            unique_together={('rolcode', 'devicecode')},
        ),
    ]
