# Generated by Django 3.0.1 on 2021-10-10 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_auto_20211009_2120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roluser',
            unique_together={('rolcode', 'usercode')},
        ),
    ]
