# Generated by Django 3.2.5 on 2021-07-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_auto_20210722_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
